### PR TITLE
getProductsByJson returns all the data

### PR DESCRIPTION
**Pull request by MicaCblls**
Add functionality to getProductsByJson function

### CODE REVIEW

**Comment by AntilopeDisecado** [comment]
Joya

**Comment by gabrielCarrenio** [comment]
all okey

**Review by AntilopeDisecado — APPROVED** [review]

**Comment by gabrielCarrenio** [comment]
okey

**Comment by gabrielCarrenio** [comment]
okey

**Review by gabrielCarrenio — APPROVED** [review]

**Pull request merged**
